### ISSUE TITLE
remove suggestions for users that I already follow

### ISSUE THREAD

**Issue by henningninneh** [gabipurcaru/followgraph#1]
This is an excellent idea. Unfortunately, there are many suggestions among the results for users that I already follow. DetersHenning@eupolicy.social

Best wishes
H

**Comment by gabipurcaru** [comment]
hey @henningninneh, thanks for flagging. As far as I can tell, this is because you follow more than 240 people, and anyone beyond that is not seen as a followee. I've increased the limit to 2000. Can you check whether the issue is still there?

Thanks.

**Comment by henningninneh** [comment]
seems to work. thanks a lot!

**Comment by ineffyble** [comment]
I'm hitting this. Unfortunately I'm following just over 5000 people.
