### ISSUE TITLE
Attribution to hero image?

### ISSUE THREAD

**Issue by untitaker** [gabipurcaru/followgraph#26]
Can you tell me who made this picture you're using on the site and which license it is under? Thanks!

![](https://followgraph.vercel.app/_next/image?url=%2Fhero.png&w=640&q=75)

**Comment by gabipurcaru** [comment]
The image is made with Midjourney AI, which grants rights for any use without attribution.

![Screenshot_20221230-133733](https://user-images.githubusercontent.com/828897/210076204-214efe5c-f13d-4812-829e-688eca4ad56c.jpg)
