### ISSUE TITLE
Feat: Download as CSV

### ISSUE THREAD

**Issue by ayoayco** [gabipurcaru/followgraph#32]
Mastodon allows following multiple accounts by uploading a .csv file.

Having a “download all as csv” would be nice for this, and maybe even having checkboxes to select accounts that will be included in the CSV file.

**Comment by gabipurcaru** [comment]
hey, see discussion in #6. I do agree this would be a useful feature, but I'm also worried about misuse

**Comment by ayo-run** [comment]
@gabipurcaru Ah missed that. Thanks!
