### ISSUE TITLE
csv export for top n suggestions

### ISSUE THREAD

**Issue by joshbalfour** [gabipurcaru/followgraph#6]
Love this tool!

I think it'd be really cool to be able to csv export the top 50/100/200 suggestions so I can bulk import them easily into mastodon.

Happy to PR this after Christmas!

**Comment by ppamidimarri** [comment]
I would love to see this as well!

**Comment by gabipurcaru** [comment]
Yea, I get it :) the feature _would_ be super useful. But I'm worried about the potential for abuse with such a feature, so I will not add it. Instead, I'm adding an FAQ item in #21 explaining the reasoning
